"""Reject unexpected files or changed project sources in release archives."""

from __future__ import annotations

import hashlib
import re
import stat
import sys
import tarfile
import tomllib
import zipfile
from pathlib import Path, PurePosixPath


ROOT = Path(__file__).resolve().parents[1]
VERSION = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))["project"]["version"]
PACKAGE = "agent_shuttle"
DIST_INFO = f"{PACKAGE}-{VERSION}.dist-info"
SDIST_ROOT = f"{PACKAGE}-{VERSION}"
EGG_INFO = "src/agent_shuttle.egg-info"
EGG_FILES = {
    "PKG-INFO", "SOURCES.txt", "dependency_links.txt", "entry_points.txt",
    "requires.txt", "top_level.txt",
}
SENSITIVE = {
    "GitLab token": rb"glpat-[A-Za-z0-9_.-]{20,}",
    "GitHub token": rb"gh[pousr]_[A-Za-z0-9_]{30,}",
    "PyPI token": rb"pypi-[A-Za-z0-9_-]{30,}",
    "private key": rb"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----",
    "AWS access key": rb"AKIA[0-9A-Z]{16}",
}


def source_files() -> dict[str, bytes]:
    files = [ROOT / "src" / PACKAGE / "__init__.py"]
    files += list((ROOT / "src" / PACKAGE).glob("*.py"))
    return {path.relative_to(ROOT).as_posix(): path.read_bytes() for path in set(files)}


def check_name(name: str) -> None:
    parts = PurePosixPath(name).parts
    if (not parts or name.startswith("/") or "\\" in name
            or any(part in {".", ".."} for part in parts)):
        raise AssertionError(f"Unsafe archive member: {name}")


def check_content(name: str, data: bytes) -> None:
    for label, pattern in SENSITIVE.items():
        if re.search(pattern, data):
            raise AssertionError(f"Possible {label} in {name}")


def verify_wheel(path: Path, sources: dict[str, bytes]) -> None:
    expected_modules = {name.removeprefix("src/") for name in sources}
    seen_modules: set[str] = set()
    seen_names: set[str] = set()
    with zipfile.ZipFile(path) as archive:
        for member in archive.infolist():
            name = member.filename
            check_name(name)
            if name in seen_names:
                raise AssertionError(f"Duplicate wheel member: {name}")
            seen_names.add(name)
            member_type = stat.S_IFMT(member.external_attr >> 16)
            if member_type not in {0, stat.S_IFREG, stat.S_IFDIR}:
                raise AssertionError(f"Unexpected wheel member type: {name}")
            if member.is_dir():
                continue
            if name.startswith(f"{DIST_INFO}/"):
                relative = name.removeprefix(f"{DIST_INFO}/")
                if relative not in {"METADATA", "WHEEL", "RECORD", "entry_points.txt", "top_level.txt", "licenses/LICENSE"}:
                    raise AssertionError(f"Unexpected wheel metadata: {name}")
            elif name in expected_modules:
                seen_modules.add(name)
                if archive.read(member) != sources[f"src/{name}"]:
                    raise AssertionError(f"Wheel differs from checked-out source: {name}")
            else:
                raise AssertionError(f"Unexpected wheel file: {name}")
            check_content(name, archive.read(member))
    if seen_modules != expected_modules:
        raise AssertionError(f"Missing wheel modules: {expected_modules - seen_modules}")
    required_metadata = {f"{DIST_INFO}/{name}" for name in
                         ("METADATA", "WHEEL", "RECORD", "entry_points.txt")}
    if not required_metadata.issubset(seen_names):
        raise AssertionError(f"Missing wheel metadata: {required_metadata - seen_names}")
    print(f"wheel: {len(seen_modules)} verified modules; sha256={hashlib.sha256(path.read_bytes()).hexdigest()}")


def verify_sdist(path: Path, sources: dict[str, bytes]) -> None:
    seen_modules: set[str] = set()
    seen_names: set[str] = set()
    with tarfile.open(path, "r:gz") as archive:
        for member in archive:
            check_name(member.name)
            if member.name in seen_names:
                raise AssertionError(f"Duplicate sdist member: {member.name}")
            seen_names.add(member.name)
            if member.isdir():
                continue
            if not member.isfile():
                raise AssertionError(f"Unexpected sdist member type: {member.name}")
            prefix = f"{SDIST_ROOT}/"
            if not member.name.startswith(prefix):
                raise AssertionError(f"Unexpected sdist root: {member.name}")
            name = member.name.removeprefix(prefix)
            if name in sources:
                seen_modules.add(name)
                expected = sources[name]
            elif name in {"LICENSE", "README.md", "pyproject.toml"}:
                expected = (ROOT / name).read_bytes()
            elif name in {"PKG-INFO", "setup.cfg"}:
                expected = None  # Generated by setuptools.
            elif name.startswith(f"{EGG_INFO}/") and name.removeprefix(f"{EGG_INFO}/") in EGG_FILES:
                expected = None  # Generated by setuptools.
            elif name.startswith("tests/") and re.fullmatch(r"tests/test_[a-z0-9_]+\.py", name):
                expected = (ROOT / name).read_bytes()
            else:
                raise AssertionError(f"Unexpected sdist file: {name}")
            stream = archive.extractfile(member)
            if stream is None:
                raise AssertionError(f"Unreadable sdist member: {name}")
            data = stream.read()
            if expected is not None and data != expected:
                raise AssertionError(f"Sdist differs from checked-out source: {name}")
            check_content(name, data)
    if seen_modules != set(sources):
        raise AssertionError(f"Missing sdist modules: {set(sources) - seen_modules}")
    print(f"sdist: {len(seen_modules)} verified modules; sha256={hashlib.sha256(path.read_bytes()).hexdigest()}")


def main() -> None:
    dist = Path(sys.argv[1] if len(sys.argv) > 1 else "dist")
    wheel = list(dist.glob(f"{PACKAGE}-{VERSION}-*.whl"))
    sdist = list(dist.glob(f"{PACKAGE}-{VERSION}.tar.gz"))
    if len(wheel) != 1 or len(sdist) != 1 or len(list(dist.iterdir())) != 2:
        raise AssertionError("Expected exactly one wheel and one sdist for this version")
    sources = source_files()
    verify_wheel(wheel[0], sources)
    verify_sdist(sdist[0], sources)


if __name__ == "__main__":
    main()
